name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Run
        run: dotnet run
      - name: Generate index.mp4
        run: docker-compose run generate_index_video
      - name: Generate poster.mp4
        run: docker-compose run generate_poster_video
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }} # PRではDeployしない
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dst
          force_orphan: true
